config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'
  get 'searches/search'
  # get 'relasionships/create'
  # get 'relasionships/destroy'
  # get 'book_comments/create'
  # get 'book_comments/destroy'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to:"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]do
    resource :favorite,only: [:create, :destroy]
    resources :book_comments,only: [:create, :destroy]
  end
  #ユーザーにフォロー機能をネストさせてこのユーザーをフォローするといったアクションでユーザー指定できるようにする
  resources :users, only: [:new, :index,:show,:edit,:update]do
    resources :relationships,only: [:create, :destroy,]
  end
  resources :users do
    #member doを使うことで特定のユーザーidを紐づけてそのユーザーのfollowings,followersをget,一覧で表示できるように
    member do
     get :followings, :followers
    end
  end
  resources :searches, only: [:search]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :index, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create

    @book = Book.find(params[:book_id])#bookモデルを通して持ってきたbook_idと同じ箇所を探して（今回は同じidの数字）紐付けする
    @book_comment = current_user.book_comments.new(book_comment_params)#コメントはどのユーザーがしたか分からないといけないためcurrent_userのデータテーブルbook_commentsにあるbook_idと前述で持ってきたidを紐付けている
    @book_comment.book_id = @book.id
    @book_comment.save
    # pp @book
    # pp @book_comment
    # pp @book_comment.book
    # redirect_to book_path(@book.id)
  end

  def destroy
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.find_by(book_id: @book.id)
    @book_comment　= BookComment.find(params[:id]).destroy
    # redirect_to book_path(@book.id)
  end
  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_book_comment.html.erb
<% book.book_comments.each do |book_comment| %>
  <tr>
    <td><%= link_to(book_comment.user, remote: true) do %>
      <%= image_tag book_comment.user.get_profile_image, size:"50x50" %><br />
      <%= book_comment.user.name %>
    <% end %></td>
    <td><%= book_comment.comment %></td>
      <% if book_comment.user_id == current_user.id %>
        <td><%= link_to "Destroy",book_book_comment_path(book,book_comment), method: :delete, remote: true ,class: "btn btn-sm btn-danger" %></td>
      <% end %>
  </tr>
<% end %>

app/views/book_comments/_count.html.erb
コメント数：<%= book.book_comments.count %>

app/views/book_comments/_form.html.erb
<%= form_with model: book_comment, url: book_book_comments_path(book.id) ,method: :post ,local: false do |f| %>
  <%= f.text_area :comment,placeholder: "コメントをここに", cols:80,rows:5, id: "comment_textarea" %><br />
  <%= f.submit "送信"%>
<% end %>

app/views/book_comments/create.js.erb
$('#book_comments_index').html("<%= j(render 'book_comments/book_comment', book: @book) %>");
$('#book_comments_count').html("<%= j(render 'book_comments/count', book: @book_comment.book) %>");
$('#comment_textarea').val("");

app/views/book_comments/destroy.js.erb
$('#book_comments_index').html("<%= j(render 'book_comments/book_comment', book: @book) %>");
$('#book_comments_count').html("<%= j(render 'book_comments/count', book: @book_comment.book) %>");