config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'
  get 'searches/search'
  # get 'relasionships/create'
  # get 'relasionships/destroy'
  # get 'book_comments/create'
  # get 'book_comments/destroy'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to:"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]do
    resource :favorite,only: [:create, :destroy]
    resources :book_comments,only: [:create, :destroy]
  end
  #ユーザーにフォロー機能をネストさせてこのユーザーをフォローするといったアクションでユーザー指定できるようにする
  resources :users, only: [:new, :index,:show,:edit,:update]do
    resources :relationships,only: [:create, :destroy,]
  end
  resources :users do
    #member doを使うことで特定のユーザーidを紐づけてそのユーザーのfollowings,followersをget,一覧で表示できるように
    member do
     get :followings, :followers
    end
  end
  resources :searches, only: [:search]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :index, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  #自分がフォロー、アンフォローする記述、されたの関係。ユーザーモデルが多くのRelationshipのレコードを持つためhas_manyで記述している。１つ目の記述は仮想のテーブル名で名前自分で命名する。2つ目で紐付けるモデル名。３つ目はこの外部キーに保存してといった記述relationshipsは中間テーブル
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  #相手がフォロー、アンフォローする記述(一覧画面で使う)上の記述のみでフォローアンフォローはできるようになる
  has_many :reverse_of_relationships, class_name:"Relationship", foreign_key: "followed_id", dependent: :destroy
  #一覧画面で使う
  #フォローした人を上記で定義したrelationshipsメソッドを使ってフォローしてくれてる人(followed)の情報を引っ張ってこれる
  has_many :followings, through: :relationships, source: :followed
  #フォローされている人を上記で定義したreverse_of_relationshipsメソッドを使ってフォローした人の情報を引っ張ってこれる(followerテーブルを元に)
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  #フォローした時の処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  #フォロー外す時の処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  #フォローしているかの判定
  def following?(user)
    followings.include?(user)
  end
  def self.looks(search,word)
    if search =="perfect_match"
      @user = User.where("name LIKE ?", "#{word}")#nameカラムからwhereでUserモデルから、LIKEで後ろに書かれた同じ文字列(wordから)を探してくる（？は入力で指定された値になる）
    elsif search == "pertial_match"
      @user = User.where("name LIKE ?", "%#{word}%")
    else
      @user =User.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]
  before_action :set_user, only: [:followings, :followers]

  def show
    @user = User.find(params[:id])
    @current_entry = Entry.where(user_id: current_user.id)
    @another_entry = Entry.where(user_id: @user.id)
    @books = @user.books
    @book = Book.new
    @is_room = false
    @room_id = nil
    unless @user.id == current_user.id
      @current_entry.each do |current|
        @another_entry.each do |another|
          if current.room_id == another.room_id
            @is_room = true
            @room = current.room_id
          end
        end
      end
      unless @is_room
        @room = Room.new
        @entry = Entry.new
      end
    end
  end


  def index
    @user = current_user
    @relationship = @user.relationships
    @users = User.all
    @book = Book.new

  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else

      render :edit
    end
  end
  def followings
    @users = @user.followings
  end

  def followers
    @users = @user.followers
  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
      <th colspan="3"></th>
      <th colspan="3"></th>
      <th colspan="3"></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followings.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <% if user != current_user  %>
          <% if current_user.following?(user) %>
            <td><%= link_to "フォロー外す", user_relationship_path(user,current_user) , method: :delete %></td>
          <% else %>
            <td><%= link_to "フォローする", user_relationships_path(user,current_user), method: :post %></td>
          <% end %>
        <% end %>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to(followings_user_path(user)) do %>
    <%= user.followings.count %>
    <% end %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to(followers_user_path(user)) do %>
    <%= user.followers.count %>
    <% end %></th>
  </tr>
</table>
  <div class='col'>
    <% if user == current_user %>
      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    <% else %>
      <% if current_user.following?(user) %>
        <%= link_to user_relationship_path(user,current_user), method: :delete, class:"btn btn-info btn-block"  do %>
          フォロー外す
        <% end %>
        <% unless user == current_user %>
          <% if is_room == true %>
            <%= link_to room_path(room), class:"btn btn-light btn-block" do %>
              メッセージを送る
            <% end %>
          <% else %>
            <%= form_with model: room, url: rooms_path do |f| %>
              <%= fields_for entry do |e| %>
                <%= e.hidden_field :user_id, value: user.id %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% else %>
        <%= link_to user_relationships_path(user), method: :post, class:"btn btn-success btn-block"  do %>
          フォローする
        <% end %>
      <% end %>
    <% end %>
  </div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h1>Follower Users</h1>
<% if @users.exists? %>
   <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <% @users.each do |user| %>
      <tbody>
        <tr>
          <td><%= image_tag user.get_profile_image, size:'100x100' %></td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
          <td><%= link_to "Show", user_path(user) %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
<% else %>
    <p>ユーザーはいません</p>
<% end %>

app/views/users/followings.html.erb
<h1>Follow Users</h1>
<% if @users.exists? %>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <% @users.each do |user| %>
      <tbody>
        <tr>
          <td><%= image_tag user.get_profile_image, size:'100x100' %></td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
          <td><%= link_to "Show", user_path(user) %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'info', user: @user %>

      <h2 class="mt-3">New book</h2>
      <%= render '/books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user, relationsip: @relationsip, is_room: @is_room, room: @room, entry: @entry %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>