config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'
  get 'searches/search'
  # get 'relasionships/create'
  # get 'relasionships/destroy'
  # get 'book_comments/create'
  # get 'book_comments/destroy'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to:"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]do
    resource :favorite,only: [:create, :destroy]
    resources :book_comments,only: [:create, :destroy]
  end
  #ユーザーにフォロー機能をネストさせてこのユーザーをフォローするといったアクションでユーザー指定できるようにする
  resources :users, only: [:new, :index,:show,:edit,:update]do
    resources :relationships,only: [:create, :destroy,]
  end
  resources :users do
    #member doを使うことで特定のユーザーidを紐づけてそのユーザーのfollowings,followersをget,一覧で表示できるように
    member do
     get :followings, :followers
    end
  end
  resources :searches, only: [:search]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :index, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    room = Room.create
    current_entry = Entry.create(user_id: current_user.id, room_id: room.id)
    another_entry = Entry.create(user_id: params[:entry][:user_id], room_id: room.id)
    redirect_to room_path(room)
  end

  def index
    # ログインユーザー所属ルームID取得
    current_entries = current_user.entries
    my_room_id = []
    current_entries.each do |entry|
      my_room_id << entry.room.id
    end
    # 自分のroom_idでuser_idが自分じゃないのを取得
    @another_entries = Entry.where(room_id: my_room_id).where.not(user_id: current_user.id)
  end

  def show
    @room = Room.find(params[:id])
    @messages = @room.messages.all
    @message = Message.new
    @entries = @room.entries
    @another_entry = @entries.where.not(user_id: current_user.id).first
  end
end 

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<% @another_entries.each do |entry| %>
  <%= link_to room_path(entry.room) do %>
    <div class="card">
      <div class="card-body">
        <div class="d-flex">
          <div class="chat-avatar">
            <%= link_to user_path(entry.user) do %>
              <%= image_tag entry.user.avatar_image %>
            <% end %>
          </div>
          <div class="chat-user-name">
            <%= entry.user.display_name %>
          </div>
        </div>
        <div class="chat-text">
          <% message = Message.find_by(id: entry.room.message_ids.last) %>
          <%= message&.body %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/rooms/show.html.erb
<div class="title">
  <h2>
    <%= "#{@another_entry.user.email}さんとのメッセージ" %>
  </h2>
</div>

<% @messages.each do |m| %>
  <% if m.user_id == current_user.id %>
    <div class="mycomment">
      <p>
        <%= m.body %>
      </p>
    </div>
  <% else %>
    <div class="fukidasi">
      <div class="faceicon">
        <%= image_tag m.user.email %>
      </div>
      <div class="chatting">
        <div class="says">
          <p>
            <%= m.body %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

<div class="chat-form-box">
  <%= form_for @message do |f| %>
    <div class="chat-form-group">
      <%= f.text_field :body %>
      <%= f.hidden_field :room_id, value: @room.id %>
      <%= f.submit "送信する" %>
    </div>
  <% end %>
</div>