config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'
  get 'searches/search'
  # get 'relasionships/create'
  # get 'relasionships/destroy'
  # get 'book_comments/create'
  # get 'book_comments/destroy'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to:"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]do
    resource :favorite,only: [:create, :destroy]
    resources :book_comments,only: [:create, :destroy]
  end
  #ユーザーにフォロー機能をネストさせてこのユーザーをフォローするといったアクションでユーザー指定できるようにする
  resources :users, only: [:new, :index,:show,:edit,:update]do
    resources :relationships,only: [:create, :destroy,]
  end
  resources :users do
    #member doを使うことで特定のユーザーidを紐づけてそのユーザーのfollowings,followersをget,一覧で表示できるように
    member do
     get :followings, :followers
    end
  end
  resources :searches, only: [:search]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :index, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to:user
  has_many:favorites, dependent: :destroy
  has_many:favorited_users, through: :favorites, source: :user
  has_many :book_comments, dependent: :destroy
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  def book_commented_by?(user)
    book_comments.exists?(user_id: user.id)
  end
  def self.looks(search,word)
    if search == "perfect_match"
      @book =Book.where("title LIKE?","#{word}")
    elsif search == "perfcial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book =Book.all
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to:book
  belongs_to:user
  validates :user_id, uniqueness: {scope: :book_id}
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :body, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  #ユーザーモデルへのアソシエーション。follower(id)カラムがユーザーモデルに所属していることを定義する
  belongs_to :follower, class_name:"User"
  belongs_to :followed, class_name:"User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  #自分がフォロー、アンフォローする記述、されたの関係。ユーザーモデルが多くのRelationshipのレコードを持つためhas_manyで記述している。１つ目の記述は仮想のテーブル名で名前自分で命名する。2つ目で紐付けるモデル名。３つ目はこの外部キーに保存してといった記述relationshipsは中間テーブル
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  #相手がフォロー、アンフォローする記述(一覧画面で使う)上の記述のみでフォローアンフォローはできるようになる
  has_many :reverse_of_relationships, class_name:"Relationship", foreign_key: "followed_id", dependent: :destroy
  #一覧画面で使う
  #フォローした人を上記で定義したrelationshipsメソッドを使ってフォローしてくれてる人(followed)の情報を引っ張ってこれる
  has_many :followings, through: :relationships, source: :followed
  #フォローされている人を上記で定義したreverse_of_relationshipsメソッドを使ってフォローした人の情報を引っ張ってこれる(followerテーブルを元に)
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  #フォローした時の処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  #フォロー外す時の処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  #フォローしているかの判定
  def following?(user)
    followings.include?(user)
  end
  def self.looks(search,word)
    if search =="perfect_match"
      @user = User.where("name LIKE ?", "#{word}")#nameカラムからwhereでUserモデルから、LIKEで後ろに書かれた同じ文字列(wordから)を探してくる（？は入力で指定された値になる）
    elsif search == "pertial_match"
      @user = User.where("name LIKE ?", "%#{word}%")
    else
      @user =User.all
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @bookn = Book.new
    @user = @book.user
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
  end
  
  def index
    @books = Book.includes(:favorited_users).sort{|a,b| b.favorited_users.size <=> a.favorited_users.size}
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    # @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
    if @user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else

      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    room = Room.create
    current_entry = Entry.create(user_id: current_user.id, room_id: room.id)
    another_entry = Entry.create(user_id: params[:entry][:user_id], room_id: room.id)
    redirect_to room_path(room)
  end

  def index
    # ログインユーザー所属ルームID取得
    current_entries = current_user.entries
    my_room_id = []
    current_entries.each do |entry|
      my_room_id << entry.room.id
    end
    # 自分のroom_idでuser_idが自分じゃないのを取得
    @another_entries = Entry.where(room_id: my_room_id).where.not(user_id: current_user.id)
  end

  def show
    @room = Room.find(params[:id])
    @messages = @room.messages.all
    @message = Message.new
    @entries = @room.entries
    @another_entry = @entries.where.not(user_id: current_user.id).first
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%=  link_to users_path,class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> users
            <% end %>
          </li>
          <li>
            <%=  link_to books_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> books
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> log out
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%= link_to(home_about_path,class: 'nav-link text-light') do %>
              <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to(new_user_registration_path,class:'nav-link text-light') do %>
              <i class="fas fa-user-plus"></i> Sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> Log in
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/c7fcadd3b5.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <main>
        <% if user_signed_in? %>
        <div class = "container">
          <div class = "row">
             <div class="serch-form mx-auto mt-3 mb-3 col-mt-12 " >
                <%= form_with url: searches_search_path, method: :get do |f| %>
                  <%= f.text_field :word %>
                  <%= f.select :range, options_for_select([['User'],['Book']]) %>
                  <%= f.select :search, options_for_select([["完全一致","perfect_match"],["部分一致","pertial_match"]]) %>
                  <%= f.submit "検索" %>
                <% end %>
            </div>
          </div>
        </div>
        <% end %>
        <%= yield %>
        <p id="notice"><%= notice %></p>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>